cart_app/urls.py
from django.urls import path

from .views import view_cart, add_product, remove_product, clear

app_name = 'cart_app'

urlpatterns = [
    path('', view_cart, name='view'),
    path('add/', add_product, name='add'),
    path('remove/', remove_product, name='remove'),
    path('set/', add_product, name='set'),
    path('clear/', clear, name='clear'),
]

my_store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static

from my_store_app import urls as my_store_urls
from cart_app import urls as cart_urls
from my_store_auth_app import urls as auth_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(my_store_urls, namespace='store')),
    path('cart/', include(cart_urls, namespace='cart')),
    path('auth/', include(auth_urls, namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_store_app/urls.py
from django.urls import path

from .views import view_category, view_product, make_order

app_name = 'my_store_app'

urlpatterns = [
    path('', view_category, name='index'),
    path('category/<int:category_id>', view_category, name='category'),
    path('product/<int:product_id>', view_product, name='product'),
    path('order/', make_order, name='order'),
]

my_store_auth_app/urls.py
from django.urls import path
from my_store_auth_app.views import login_view, logout_view, signup_view

app_name = 'my_store_auth_app'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup')
]

my_store_app/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import RegexValidator


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название')

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:category', args=[self.pk])


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название')
    category = models.ManyToManyField(Category,
                                      blank=True,
                                      related_name='category',
                                      verbose_name='Категория',
                                      )
    description = models.TextField(max_length=3000, blank=True, verbose_name='Описание')
    image = models.ImageField(upload_to='my_store_app/images/products/%Y/%m/%d/', null=True, blank=True,
                              verbose_name='Изображение')
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Цена")
    stock = models.PositiveIntegerField(verbose_name='В наличии')
    available = models.BooleanField(default=True, verbose_name='Доступен')
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    date_updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено')

    class Meta:
        ordering = ['-date_created']
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product', args=[self.pk])


def get_sentinel_product():
    """
    Возвращает объект класса Product (или создает и возвращает, если его нет) для замещения удаленных объектов этого
    класса.
    """
    return Product.objects.get_or_create(name='deleted')[0]


class Order(models.Model):
    customer_name = models.CharField(max_length=100, verbose_name='Имя покупателя')

    # Валидатор для номера телефона
    phone_regex = RegexValidator(regex=r'^(?:(?:\+7)|8)\d{10}$', message="Номер должен быть в формате \"+7ХХХХХХХХХХ\" "
                                                                         "или \"8ХХХХХХХХХХ\".")
    phone_number = models.CharField(validators=[phone_regex], max_length=15, verbose_name='Номер телефона')
    email = models.EmailField(blank=True, verbose_name='Электронная почта')

    pickup = models.BooleanField(default=False, verbose_name='Самовывоз')
    delivery_address = models.CharField(max_length=150, blank=True, verbose_name='Адрес доставки')
    comment = models.CharField(max_length=500, blank=True, verbose_name='Комментарий')
    received = models.BooleanField(default=False, verbose_name='Получено')
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        ordering = ['-date_created']
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Заказ №%s' % self.pk

    def get_full_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE, null=True, verbose_name='Заказ')
    product = models.ForeignKey(Product, on_delete=models.SET(get_sentinel_product), verbose_name='Товар')
    quantity = models.PositiveIntegerField(verbose_name='Количество')
    purchase_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена покупки')

    def get_cost(self):
        return self.purchase_price * self.quantity

my_store_app/forms.py
from django.forms import ModelForm, TextInput, Textarea, CheckboxInput

from .models import Order

TEXT_INPUT = TextInput(attrs={'class': 'form-control'})


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = [
            'customer_name',
            'phone_number',
            'email',
            'pickup',
            'delivery_address',
            'comment',
        ]
        widgets = {
            'customer_name': TEXT_INPUT,
            'phone_number': TEXT_INPUT,
            'email': TEXT_INPUT,
            'pickup': CheckboxInput(attrs={'class': 'form-inline'}),
            'delivery_address': TEXT_INPUT,
            'comment': Textarea(attrs={
                'class': 'form-control',
                'rows': 3,
            }),
        }
        labels = {
            'customer_name': 'Имя*',
            'phone_number': 'Номер телефона*',
            'pickup': 'Самовывоз',
            'delivery_address': 'Полный адрес',
            'comment': 'Комментарий',
        }

my_store_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.views.decorators.http import require_http_methods

from .models import Category, Product, OrderItem
from .forms import OrderForm
from cart_app.cart import Cart
from .tasks import send_order_email

# Create your views here.


def view_category(request, category_id=None):
    if request.method == 'GET':
        categories = Category.objects.all()

        if category_id:
            category = get_object_or_404(Category, pk=category_id)
            product_list = Product.objects.filter(available=True, category=category)
        else:
            category = None
            product_list = Product.objects.filter(available=True)

        paginator = Paginator(product_list, 12)
        page = request.GET.get('page')
        products = paginator.get_page(page)

        context = {'categories': categories,
                   'products': products,
                   'category': category,
                   }
        return render(request, 'my_store_app/index.html', context)

    return HttpResponse(status=405)


def view_product(request, product_id):
    if request.method == 'GET':
        product = get_object_or_404(Product, pk=product_id)
        categories = Category.objects.all()

        context = {'categories': categories,
                   'product': product,
                   }

        return render(request, 'my_store_app/product.html', context)

    return HttpResponse(status=405)


@require_http_methods(['GET', 'POST'])
def make_order(request):
    form = OrderForm()

    # Создание заказа по методу POST
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save()

            cart = Cart(request)

            # Защита от создания пустых заказов
            if not len(cart):
                return HttpResponse(status=400)

            for item in cart:
                product = item['product']
                purchase_price = item['price']
                quantity = item['quantity']

                OrderItem.objects.create(order=order, product=product, purchase_price=purchase_price, quantity=quantity)

            cart.clear()

            # Отправка сообщения асинхронно на электронную почту
            if form.cleaned_data['email']:
                send_order_email.delay(order.pk)

            return render(request, 'my_store_app/order_success.html', {'order': order})

    return render(request, 'my_store_app/order.html', {'form': form})

my_store_app/templates/my_store_app/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap links -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <!-- My links -->
    <link rel="stylesheet" href="{% static 'my_store_app/styles.css' %}">
    {% block javascript %}{% endblock %}
</head>
<body>
        <div class="jumbotron text-center" style="margin-bottom:0">
            <h1>Мой интернет-магазин</h1>
        </div>

        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <div class="mx-auto">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                    <span>Меню</span>
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'store:index' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <div id="cart">
                            <a class="nav-link" href="{% url 'cart:view' %}">{% if cart|length > 0 %}Корзина ({{ cart|length }}) на {{ cart.get_total_price }} руб.{% else %}Корзина пуста{% endif %}</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <div id="auth-nav">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="#">{{ user.username }}</a>
                        {% else %}
                            <a class="nav-link" href="#" data-toggle="modal" data-target="#authModal">Авторизоваться</a>
                        {% endif %}
                        </div>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="#" onclick="logOut()">Деавторизоваться</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <!-- The Modal -->
        <div class="modal fade" id="authModal">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Авторизация</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <div class="form-group">
                        <label for="usr">Логин:</label>
                        <input type="text" class="form-control" id="usr" name="username">
                    </div>

                    <div class="form-group">
                        <label for="pwd">Пароль:</label>
                        <input type="password" class="form-control" id="pwd" name="password">
                    </div>

                    <div id="message">
                        <!-- Message if login or password is incorrect -->
                    </div>

                    <div id="buttons" style="display: inline;">
                        <button type="submit" class="btn btn-primary" onclick="logIn()">Войти</button>
                        <a href="{% url 'auth:signup' %}">
                            <button style="float: right;" type="submit" class="btn btn-secondary">Регистрация</button>
                        </a>
                    </div>

                </div>

              </div>
            </div>
          </div>

        {% block content %}
            Content
        {% endblock %}

        <div class="jumbotron text-center" style="margin-bottom:0">
            <p>Footer</p>
        </div>

        <script>
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            var csrftoken = getCookie('csrftoken');

            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });

            var logIn;
            var logOut;
            $(document).ready(function(){
            logIn = function(id){
                $.ajax({
                url: '{% url "auth:login" %}',
                type: 'POST',
                data: {
                    'username': $("#usr").val(),
                    'password': $("#pwd").val()
                },
                success: function(data) {
                    if (data['message'] === 'authorized') {
                        $('#authModal').modal("hide");
                        $("#collapsibleNavbar").load(" #collapsibleNavbar");
                    } else if (data['message'] === 'invalid login') {
                        $("#message").empty().append("<p style='color: red;'>Неправильный логин или пароль</p>");
                    }
                }
                });
            }
            logOut = function(id){
                $.ajax({
                url: '{% url "auth:logout" %}',
                success: function() {
                    $("#collapsibleNavbar").load(" #collapsibleNavbar");
                    }
                });
            }
        });
        </script>

</body>
</html>

my_store_app/templates/my_store_app/index.html
{% extends 'my_store_app/_base.html' %}
{% load staticfiles %}

{% block title %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Все товары
    {% endif %}
{% endblock %}

{% block javascript %}
    <script>
        var addToCart;
        $(document).ready(function(){
            addToCart = function(id){
                $.ajax({
                url:'{% url "cart:add" %}',
                cache: false,
                data: {
                    'id': id
                },
                success: function(){
                    $("#cart").load(" #cart");
                    alert('Товар добавлен в корзину.');
                }
                });
            }
        });
    </script>
{% endblock %}


{% block content %}
    <div class="container-fluid">
        <div class="row">
            <!-- Sidebar for categories-->
            <div class="col-sm-2">
                <h3 align="center">Категории</h3>
                <ul class="sidebar">
                    <li {% if not category %} class="selected" {% endif %}>
                        <a href="{% url 'store:index' %}">Все</a>
                    </li>
                    {% for ctg in categories %}
                        <li {% if ctg.pk == category.pk %} class="selected" {% endif %}>
                            <a href="{{ ctg.get_absolute_url }}">{{ ctg.name }}</a>
                        </li>
                    {% endfor %}
                </ul>

            </div>
            <!-- Products -->
            <div class="col-sm-10">
                <div class="d-flex flex-wrap">
                    {% for product in products %}
                        {% if product.available %}
                            <div class="product-box shadow-sm">
                                <a href="{{ product.get_absolute_url }}">
                                    <div class="image-box">
                                        <img class="product-image" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "images/no-image.png" %}{% endif %}" alt="product image">
                                    </div>
                                </a>
                                <div class="product-box-body">
                                    <div class="text-box">
                                        <p>{{ product.name }}</p>
                                    </div>

                                    <div class="price-box">
                                        <p>{{ product.price }} руб.</p>
                                    </div>

                                    <div class="button-box">
                                        {% if product.stock > 0 %}
                                            <input value="Добавить в корзину" type="button" class="btn btn-primary" onclick="addToCart('{{ product.pk }}')" style="width: 300px">
                                        {% else %}
                                            <button type="button" class="btn btn-primary" disabled style="width: 300px">Нет в наличии</button>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>

                <br>

                <div class="pagination">
                    <ul class="pagination" style="margin: auto;">
                          {% if products.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
                            {% if products.previous_page_number != 1 %}
                                <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">{{ products.previous_page_number }}</a></li>
                            {% endif %}
                          {% endif %}

                            <li class="page-item active"><a class="page-link" href="#">{{ products.number }}</a></li>

                          {% if products.has_next %}
                            {% if products.next_page_number != products.paginator.num_pages %}
                                <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">{{ products.next_page_number }}</a></li>
                            {% endif %}
                            <li class="page-item"><a class="page-link" href="?page={{ products.paginator.num_pages }}">{{ products.paginator.num_pages }}</a></li>
                          {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

my_store_app/templates/my_store_app/order.html
{% extends 'my_store_app/_base.html' %}
{% load cart_tags %}

{% block title %}
    Оформление заказа
{% endblock %}

{% block javascript %}
    <script>
    $(document).ready(function(){
        if (document.getElementById("id_pickup").checked) {
          $("#delivery_address").hide();
        }

        $("#id_pickup").click(function() {
          $("#delivery_address").toggle();
        });
    });
    </script>
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Оформление заказа</h1>
        <div class="row">
            <div class="col-sm-4">
                <form action="{% url 'store:order' %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div id="{{ field.html_name }}">
                            {{ field.label_tag }} {{ field }}
                            {{ field.errors }}
                            <br>
                        </div>
                    {% endfor %}
                    <p>* – обязательные поля</p>
                    <input class="btn btn-primary" type="submit" value="Отправить">
                </form>
            </div>

            <div class="col-sm-8">
                <h3 align="center">Ваш заказ:</h3>
                <ul>
                    {% for item in cart %}
                        <li>
                            {{ item.product.name }} ({{ item.quantity }} шт.) – {{ item.quantity|multiply:item.product.price }} руб.
                        </li>
                    {% endfor %}

                </ul>
                <p align="right"><b>Итого: {{ cart.get_total_price }} руб.</b></p>
            </div>
        </div>
    </div>
{% endblock %}

my_store_app/templates/my_store_app/order_success.html
{% extends 'my_store_app/_base.html' %}

{% block title %}
    Заказ принят
{% endblock %}

{% block content %}
    <div class="container">
        <h3>Заказ принят</h3>
    <p>Благодарим за выполненный заказ! Номер заказа: {{ order.pk }}</p>
    </div>
{% endblock %}

my_store_app/templates/my_store_app/product.html
{% extends 'my_store_app/_base.html' %}
{% load staticfiles %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block javascript %}
    <script>
        var addToCart;
        $(document).ready(function(){
            addToCart = function(id){
                $.ajax({
                url:'{% url "cart:add" %}',
                cache: false,
                data: {
                    'id': id,
                    'quantity': $("#quantity").val()
                },
                success: function(){
                    $("#cart").load(" #cart");
                    alert('Товар добавлен в корзину.');
                }
                });
            }
        });
    </script>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-4">
                <img class="img-fluid" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "images/no-image.png" %}{% endif %}" alt="product image">
            </div>
            <div class="col-sm-8">
                <h1> {{ product.name }} </h1>
                <p>
                    Категория:
                    {% for category in product.category.all %}
                        <a href="{{ category.get_absolute_url }}"><span class="badge badge-pill badge-primary">{{ category.name }}</span></a>
                    {% endfor %}
                </p>
                <p> Цена: {{ product.price }} руб.</p>
                <p> В наличии: {{ product.stock }}</p>
                <span>
                    <input id="quantity" type="number" name="quantity" value="1" min="1" max="{{ product.stock }}">
                    <input type="button" class="btn btn-primary" name="add" value="Добавить в корзину" onclick="addToCart('{{ product.pk }}')">
                </span>
                <p>
                    {% if product.description %}
                        Описание: {{ product.description|linebreaks }}
                    {% else %}
                        Описание отсутствует
                    {% endif %}
                </p>
            </div>
        </div>
    </div>
{% endblock %}