cart_app/urls.py
from django.urls import path

from .views import view_cart, add_product, remove_product, clear

app_name = 'cart_app'

urlpatterns = [
    path('', view_cart, name='view'),
    path('add/', add_product, name='add'),
    path('remove/', remove_product, name='remove'),
    path('set/', add_product, name='set'),
    path('clear/', clear, name='clear'),
]

my_store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static

from my_store_app import urls as my_store_urls
from cart_app import urls as cart_urls
from my_store_auth_app import urls as auth_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(my_store_urls, namespace='store')),
    path('cart/', include(cart_urls, namespace='cart')),
    path('auth/', include(auth_urls, namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_store_app/urls.py
from django.urls import path

from .views import view_category, view_product, make_order

app_name = 'my_store_app'

urlpatterns = [
    path('', view_category, name='index'),
    path('category/<int:category_id>', view_category, name='category'),
    path('product/<int:product_id>', view_product, name='product'),
    path('order/', make_order, name='order'),
]

cart_app/models.py
from django.db import models

# Create your models here.

cart_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .cart import Cart, ItemDoesNotExist
from my_store_app.models import Product

# Create your views here.


def add_product(request):
    product_id = request.GET.get('id', None)
    quantity = request.GET.get('quantity', None)
    set_qnt = request.GET.get('set_qnt', False)

    product = get_object_or_404(Product, pk=product_id)
    if not product.available:
        return HttpResponse(status=403)

    cart = Cart(request)

    if quantity:
        try:
            quantity = int(quantity)
        # Если quantity не числовое
        except ValueError:
            return HttpResponse(status=400)

        cart.add(product=product, set_qnt=set_qnt, quantity=quantity)
    else:
        cart.add(product=product, set_qnt=set_qnt)

    return HttpResponse(status=200)


def clear(request):
    cart = Cart(request)
    cart.clear()

    return HttpResponse(status=200)


def remove_product(request):
    product_id = request.GET.get('id', None)
    cart = Cart(request)
    try:
        cart.remove(product_id)
    except ItemDoesNotExist:
        return HttpResponse(status=404)

    return HttpResponse(status=200)


def view_cart(request):
    cart = Cart(request)
    return render(request, 'cart_app/cart.html', {'cart': cart})

cart_app/templates/cart_app/cart.html
{% extends 'my_store_app/_base.html' %}
{% load cart_tags %}
{% load staticfiles %}

{% block title %}
    Корзина товаров
{% endblock %}

{% block javascript %}
    <script>
        var setQuantity;
        var removeProduct;
        $(document).ready(function(){
            setQuantity = function(product_id, val){
                $.ajax({
                url:'{% url "cart:set" %}',
                cache: false,
                data: {
                    'id': product_id,
                    'quantity': val,
                    'set_qnt': true
                    },
                success: function(){
                    location.reload();
                }
                });
            }

            removeProduct = function(product_id){
                $.ajax({
                url:'{% url "cart:remove" %}',
                cache: false,
                data: {
                    'id': product_id,
                    },
                success: function(){
                    location.reload();
                }
                });
            }
        });
    </script>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                {% if cart|length > 0 %}
                    <h1>Корзина товаров</h1>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Изображение</th>
                                <th>Товар</th>
                                <th>Количество</th>
                                <th>Цена</th>
                                <th>Сумма</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in cart %}
                                {% with product=item.product %}
                                    <tr>
                                        <td>
                                            <a href="{{ product.get_absolute_url }}">
                                                <img class="img-fluid" style="max-width: 200px; max-height: 300px;" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "images/no-image.png" %}{% endif %}" alt="product image">
                                            </a>
                                        </td>
                                        <td> {{ product.name }} </td>
                                        <td>
                                            <input type="number" name="quantity" value="{{ item.quantity }}" min="1" max="{{ item.product.stock }}" onchange="setQuantity('{{ product.pk }}', this.value)">
                                            <input type="button" class="btn btn-danger" name="remove" value="Удалить" onclick="removeProduct('{{ product.pk }}')">
                                        </td>
                                        <td> {{ item.price }} руб.</td>
                                        <td>
                                                {{ item.quantity|multiply:product.price }} руб.
                                        </td>
                                    </tr>
                                {% endwith %}
                            {% endfor %}
                            <tr>
                                <td><b>Итого</b></td>
                                <td colspan="3"></td>
                                <td>
                                    <div id="totalprice">
                                        {{ cart.get_total_price }} руб.
                                    </div>
                                    <div>
                                        <br>
                                        <a href="{% url 'store:order' %}">
                                             <input type="button" class="btn btn-primary" value="Оформить заказ">
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                {% else %}
                    <h1>Ваша корзина пуста</h1>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}